FormKey: 000807:NPCResizer.esm
EditorID: NPCResizer_ConfigTerminal
VirtualMachineAdapter:
  Scripts:
  - Name: NPCResizer_ConfigTerminalScript
    Properties:
    - MutagenObjectType: ScriptObjectProperty
      Name: Venpi_DebugEnabled
      Object: 000800:VenpiCore.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: PlayerRef
      Object: 000014:Starfield.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: NPCResizer_Enabled
      Object: 000806:NPCResizer.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: NPCResizer_UseEasterEggMode
      Object: 000800:NPCResizer.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: NPCResizer_ScalingMin
      Object: 000801:NPCResizer.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: NPCResizer_ScalingMax
      Object: 000802:NPCResizer.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: NPCResizer_ConfigTerminal
      Object: 000805:NPCResizer.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: NPCResizer_ConfigTerminal_MainMenu
      Object: 000808:NPCResizer.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: NPCResizer_ConfigTerminal_ConfigScaleMin
      Object: 000809:NPCResizer.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: NPCResizer_ConfigTerminal_ConfigScaleMax
      Object: 00080A:NPCResizer.esm
    - MutagenObjectType: ScriptStringProperty
      Name: Venpi_ModName
      Data: ResizeTheWorld
Archetype:
  MutagenObjectType: MagicEffectArchetype
  Type: Script
UnkownInt2: 3
CastType: FireAndForget
UnkownInt3: 1065353216
Flags:
- HideInUI
- Painless
- NoHitEffect
Unknown: 0x00000000000000000000000000000000000000000000
